name: KitUI
author: Infernus101
api: [3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6]
main: Infernus101\KitUI\Main
version: 1.3.0
permissions: # kit permissions - kit.<kit name>
 kit.command:
  description: kit command!
  default: true
 kit.sign:
   description: kit sign!
   default: false
commands:
  kit:
    description: Kit UI!
